import type { Metadata } from 'next';

import localFont from 'next/font/local';

import './globals.css';

const pretendardVariable = localFont({
	src: '../../public/fonts/PretendardVariable.woff2',
	variable: '--font-pretendard',
	display: 'swap',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body className={`${pretendardVariable.className} antialiased`}>{children}</body>
		</html>
	);
}
